services:
  app:
    build: .
    container_name: promissum-app
    ports:
      - "${APP_PORT:-3000}:3000"
    restart: unless-stopped
    environment:
      MOCK_DRAND: "${MOCK_DRAND:-false}"
      NEXT_PUBLIC_APP_URL: ${NEXT_PUBLIC_APP_URL:-http://localhost:3000}
    volumes:
      - ./data:/data
